development: &non_production_settings
  site_url: http://suite.bounceme.net
  site_name: Suite
  admin_email: jonmagic@gmail.com
  
test:
  <<: *non_production_settings
  
production:
  site_url: http://suite.bounceme.net
  site_name: SabreTech Suite
  admin_email: jonmagic@gmail.com
